version: '2'

services:
  vpn:
    image: matsub/ipsec-vpn-server
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
